In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import folium

pd.set_option('display.max_columns', None)  # This will show all columns
pd.set_option('display.width', None)

In [93]:
weather = pd.read_csv('wichita_weather.csv')

# Convert the 'DATE' column to datetime format
weather['DATE'] = pd.to_datetime(weather['DATE'], format='%Y-%m-%d')

# Filter for dates in the year 2024
weather_2024_df = weather[weather['DATE'].dt.year == 2024]


weather_2024_df.head(50)

        STATION                    NAME       DATE  PRCP  SNOW  SNWD
0   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-01-06  0.42   NaN   NaN
1   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-01-08  0.18   NaN   NaN
2   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-01-09  1.14   NaN   NaN
3   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-01-23  0.23   NaN   NaN
4   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-02-03  0.46   NaN   NaN
5   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-02-04  0.35   NaN   NaN
6   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-03-07  0.10   NaN   NaN
7   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-03-08  1.02   NaN   NaN
8   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-03-25  1.37   NaN   NaN
9   US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-04-02  0.14   NaN   NaN
10  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-04-07  0.02   NaN   NaN
11  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-04-16  0.15   NaN   NaN
12  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-04-18  0.03   NaN   NaN
13  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-04-26  0.20   NaN   NaN
14  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-04-28  1.05   NaN   NaN
15  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-01  0.75   NaN   NaN
16  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-04  0.25   NaN   NaN
17  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-05  0.02   NaN   NaN
18  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-07  0.02   NaN   NaN
19  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-13  0.57   NaN   NaN
20  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-15  0.07   NaN   NaN
21  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-16  0.73   NaN   NaN
22  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-20  1.25   NaN   NaN
23  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-24  0.02   NaN   NaN
24  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-26  0.79   NaN   NaN
25  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-05-31  0.30   NaN   NaN
26  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-01  0.03   NaN   NaN
27  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-02  0.00   0.0   NaN
28  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-03  0.68   NaN   NaN
29  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-04  0.30   NaN   NaN
30  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-05  1.55   NaN   NaN
31  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-06  0.00   0.0   NaN
32  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-08  0.00   0.0   NaN
33  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-09  1.25   NaN   NaN
34  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-13  0.00   0.0   NaN
35  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-19  2.10   NaN   NaN
36  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-20  0.00   0.0   NaN
37  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-22  0.00   0.0   NaN
38  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-25  0.05   NaN   NaN
39  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-06-28  0.25   NaN   NaN
40  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-04   NaN   NaN   NaN
41  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-07  0.00   0.0   NaN
42  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-11  0.00   0.0   NaN
43  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-12  0.00   0.0   NaN
44  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-13  0.00   0.0   NaN
45  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-14  0.00   0.0   NaN
46  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-15  0.00   0.0   NaN
47  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-16  0.11   NaN   NaN
48  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-26  0.00   0.0   NaN
49  US1KSSG0127  WICHITA 6.3 ENE, KS US 2024-07-28  0.07   NaN   NaN

PRCP - Precipitation


SNOW - Snowfall


SNWD - Snow depth

In [60]:
#get accident data
accident = pd.read_csv('Traffic_Accidents_2024.csv')
accident.tail(3)

# accident['DATE'] = pd.to_datetime(accident['DATE'])

,X,Y,OBJECTID,INCIDENTID,ACCIDENT_DATE,INTERSECTION,LOCATION,CROSS_STREET,CITY,STATE,POSTAL_CODE,OFFENSE_CO,OFFENSE_DE,LONGITUDE,LATITUDE,YEAR_,MONTH_,DOW_,MONTHFULL,DOWFULL,QUARTER
20811,-1.084135e+07,4.536398e+06,20812,24C535917,2024/10/25 10:25:00+00,N WEST ST & W CENTRAL AVE,W CENTRAL AVE,N WEST ST,WICHITA,KS,67203.0,6150,NON-INJURY CRASH/UNDER $1000,-97.389486,37.694776,2024,10,5,October,Friday,4
20812,6.327780e-09,5.664924e-09,20813,24C536603,2024/11/07 08:30:00+00,1200 N WOODLAWN ST,1200 N WOODLAWN ST,NaN,WICHITA,KS,0.0,7090,MOTOR VEHICLE/FIXED OBJECT,-0.000020,-0.000002,2024,11,4,November,Thursday,4
20813,6.327780e-09,5.664924e-09,20814,24C537100,2024/11/12 20:15:00+00,2280 S EISENHOWER PKY,2280 S EISENHOWER PKY,NaN,WICHITA,KS,67209.0,6105,PRIVATE PROPERTY/NON-INJURY CRASH,-0.000020,-0.000002,2024,11,2,November,Tuesday,4

In [34]:

#handle missing values if necessiary
accident['CITY'] = accident['CITY'].fillna(accident['CITY'].mode()[0])
accident['STATE'] = accident['STATE'].fillna(accident['STATE'].mode()[0])


accident.loc[(accident['LOCATION'] == '1871 W SIM PARK DR') & (accident['POSTAL_CODE'].isna()), 'POSTAL_CODE'] = 67203.0
accident.loc[(accident['LOCATION'] == '4217 W 9TH ST') & (accident['POSTAL_CODE'].isna()), 'POSTAL_CODE'] = 67212.0

accident.isnull().sum()

X                   64
Y                   64
OBJECTID             0
INCIDENTID           0
ACCIDENT_DATE        0
INTERSECTION         0
LOCATION             0
CROSS_STREET     12525
CITY                 0
STATE                0
POSTAL_CODE          0
OFFENSE_CO           0
OFFENSE_DE           0
LONGITUDE            0
LATITUDE             0
YEAR_                0
MONTH_               0
DOW_                 0
MONTHFULL            0
DOWFULL              0
QUARTER              0
dtype: int64

In [22]:
num_rows = accident.shape[0]
print(f"Number of rows in the DataFrame: {num_rows}")

Number of rows in the DataFrame: 20814

In [32]:
min_lat, max_lat = 37.5, 37.9  # Latitude bounds for Wichita
min_lon, max_lon = -97.5, -97.0  # Longitude bounds for Wichita

# Filter for rows that are outside the bounds
outside_data = accident[
    (accident['LATITUDE'] < min_lat) | (accident['LATITUDE'] > max_lat) | 
    (accident['LONGITUDE'] < min_lon) | (accident['LONGITUDE'] > max_lon)
]

# Drop rows that are outside the bounds
accident = accident.drop(outside_data.index)
print(f"Number of values outside the bounds: {outside_data.shape[0]}")

Number of values outside the bounds: 0

In [94]:
print(weather['DATE'].duplicated().sum())

accident.head()

5770

,X,Y,OBJECTID,INCIDENTID,DATE,INTERSECTION,LOCATION,CROSS_STREET,CITY,STATE,POSTAL_CODE,OFFENSE_CO,OFFENSE_DE,LONGITUDE,LATITUDE,YEAR_,MONTH_,DOW_,MONTHFULL,DOWFULL,QUARTER
0,-1.580702e+07,4.523771e+06,1,23C013957,2024-02-29,W 21ST ST N & N WACO AVE,W 21ST ST N,N WACO AVE,WICHITA,KS,67203.0,7090,MOTOR VEHICLE/FIXED OBJECT,-141.996855,37.604971,2024,2,4,February,Thursday,1
1,-1.580511e+07,4.521643e+06,2,24C000041,2024-01-01,1145 E LINCOLN ST,1145 E LINCOLN ST,NaN,WICHITA,KS,67211.0,7030,MOTOR VEHICLE/MOTOR VEHICLE IN TRANSPORT,-141.979709,37.589825,2024,1,1,January,Monday,1
2,-1.580513e+07,4.521632e+06,3,24C000041,2024-01-01,E LINCOLN ST & S IDA AVE,E LINCOLN ST,S IDA AVE,WICHITA,KS,67211.0,7030,MOTOR VEHICLE/MOTOR VEHICLE IN TRANSPORT,-141.979907,37.589743,2024,1,1,January,Monday,1
3,-1.580504e+07,4.523029e+06,4,24C000084,2024-01-01,2330 E CENTRAL AVE,2330 E CENTRAL AVE,NaN,WICHITA,KS,67214.0,6105,PRIVATE PROPERTY/NON-INJURY CRASH,-141.979034,37.599688,2024,1,1,January,Monday,1
4,-1.580542e+07,4.521992e+06,5,24C000127,2024-01-01,951 E DEWEY AVE,951 E DEWEY AVE,NaN,WICHITA,KS,67202.0,6105,PRIVATE PROPERTY/NON-INJURY CRASH,-141.982486,37.592306,2024,1,1,January,Monday,1

In [103]:
#Edit weather data so that only max weather gets shown per day
weather_daily = weather.groupby('DATE', as_index=False).sum()

print(f"Total weather rows: {len(weather_daily)}")
print(f"Unique dates in weather: {weather_daily['DATE'].nunique()}")
weather_daily.head()

Total weather rows: 366
Unique dates in weather: 366

,DATE,STATION,NAME,PRCP,SNOW,SNWD
0,2024-01-01,US1KSSG0124USC00148847US1KSSG0010US1KSSG0052US...,"WICHITA 6.3 W, KS USWICHITA WX, KS USWICHITA 3...",0.00,0.0,0.0
1,2024-01-02,US1KSSG0124USC00148847US1KSSG0010US1KSSG0052US...,"WICHITA 6.3 W, KS USWICHITA WX, KS USWICHITA 3...",0.00,0.0,0.0
2,2024-01-03,US1KSSG0124US1KSSG0179USC00148847US1KSSG0010US...,"WICHITA 6.3 W, KS USWICHITA 3.2 SE, KS USWICHI...",0.00,0.0,0.0
3,2024-01-04,US1KSSG0124US1KSSG0179USC00148847US1KSSG0010US...,"WICHITA 6.3 W, KS USWICHITA 3.2 SE, KS USWICHI...",0.00,0.0,0.0
4,2024-01-05,US1KSSG0124US1KSSG0179USC00148847US1KSSG0052US...,"WICHITA 6.3 W, KS USWICHITA 3.2 SE, KS USWICHI...",2.05,13.9,10.7

In [104]:
accident.rename(columns={'ACCIDENT_DATE': 'DATE'}, inplace=True)

# Remove the timezone from the 'DATE' column (if it has timezone info)
# accident['DATE'] = accident['DATE'].dt.tz_localize(None)

#Remove time
accident['DATE'] = pd.to_datetime(accident['DATE'], format='%Y-%m-%d')


#Merge accident dates with weather dates
merged_df = pd.merge(accident, weather_daily, on='DATE', how='left')

# Total number of rows
total_rows = len(merged_df)

# Replace all NaN values with 0
merged_df = merged_df.fillna(0)

# Count the non-zero values in each column
prcp_non_zero = (merged_df['PRCP'] != 0).sum()
snow_non_zero = (merged_df['SNOW'] != 0).sum()
snwd_non_zero = (merged_df['SNWD'] != 0).sum()

# Print the results out of total rows
print(f"Non-zero count for Rain: {prcp_non_zero} out of {total_rows}")
print(f"Non-zero count for Snow: {snow_non_zero} out of {total_rows}")
print(f"Non-zero count for Snow depth: {snwd_non_zero} out of {total_rows}")

Non-zero count for Rain: 9084 out of 20814
Non-zero count for Snow: 335 out of 20814
Non-zero count for Snow depth: 419 out of 20814

In [109]:
print(weather['DATE'].duplicated().sum())

merged_df.head(3)

5770

,X,Y,OBJECTID,INCIDENTID,DATE,INTERSECTION,LOCATION,CROSS_STREET,CITY,STATE,POSTAL_CODE,OFFENSE_CO,OFFENSE_DE,LONGITUDE,LATITUDE,YEAR_,MONTH_,DOW_,MONTHFULL,DOWFULL,QUARTER,STATION,NAME,PRCP,SNOW,SNWD
0,-1.580702e+07,4.523771e+06,1,23C013957,2024-02-29,W 21ST ST N & N WACO AVE,W 21ST ST N,N WACO AVE,WICHITA,KS,67203.0,7090,MOTOR VEHICLE/FIXED OBJECT,-141.996855,37.604971,2024,2,4,February,Thursday,1,US1KSSG0124USC00148847US1KSSG0010US1KSSG0052US...,"WICHITA 6.3 W, KS USWICHITA WX, KS USWICHITA 3...",0.0,0.0,0.0
1,-1.580511e+07,4.521643e+06,2,24C000041,2024-01-01,1145 E LINCOLN ST,1145 E LINCOLN ST,0,WICHITA,KS,67211.0,7030,MOTOR VEHICLE/MOTOR VEHICLE IN TRANSPORT,-141.979709,37.589825,2024,1,1,January,Monday,1,US1KSSG0124USC00148847US1KSSG0010US1KSSG0052US...,"WICHITA 6.3 W, KS USWICHITA WX, KS USWICHITA 3...",0.0,0.0,0.0
2,-1.580513e+07,4.521632e+06,3,24C000041,2024-01-01,E LINCOLN ST & S IDA AVE,E LINCOLN ST,S IDA AVE,WICHITA,KS,67211.0,7030,MOTOR VEHICLE/MOTOR VEHICLE IN TRANSPORT,-141.979907,37.589743,2024,1,1,January,Monday,1,US1KSSG0124USC00148847US1KSSG0010US1KSSG0052US...,"WICHITA 6.3 W, KS USWICHITA WX, KS USWICHITA 3...",0.0,0.0,0.0

In [107]:
# Optional: save the filtered data to a new CSV
#merged_df.to_csv('crash_factors.csv', index=False)